### ISSUE TITLE
mdx support?

### ISSUE THREAD

**Issue by vojtaholik** [SophieAu/gatsby-plugin-social-image#1]
hey @SophieAu, this looks awesome!

I wanted to ask whether it can be paired with `gatsby-plugin-mdx` and if there are any required steps to get it working for [sites that use schema customization](https://github.com/vojtaholik/page-query-doesnt-reflect-changes/blob/master/gatsby-node.js#L50)?

thanks!!

**Comment by SophieAu** [comment]
Hey @vojtaholik! 😊 

I've just added MDX support and released a new version (1.1.0) so that should now work out-of-the-box with no new configuration required.

About schema customization: I honestly wasn't even aware that was a thing... 😅 But I'm looking into it right now and will let you know once I've figured it out myself.

**Comment by SophieAu** [comment]
Hey @vojtaholik,

I've been looking into the schema customization (finally) and unfortunately it looks more complicated than I'm willing to write and maintain since it's not something I'd need for myself. You're of course more than welcome to look into it yourself and do a PR if you're keen.

I'm closing the issue for now but feel free to open it again if you want to work on it. 😊
